# Generated by Django 3.0.7 on 2025-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, default='team_images/default.png', null=True, upload_to='team_images/'),
        ),
    ]
