# Generated by Django 3.0.7 on 2025-06-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadApp', '0002_auto_20250608_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('project_Sponsored', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='team_images/default.png', null=True, upload_to='volunteer_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('project_Volunteered_For', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='team_images/default.png', null=True, upload_to='volunteer_images/')),
            ],
        ),
    ]
