# Generated by Django 3.0.7 on 2025-06-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadApp', '0003_sponsor_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('testimonial_text', models.TextField()),
                ('image', models.ImageField(blank=True, default='team_images/default.png', null=True, upload_to='volunteer_images/')),
            ],
        ),
    ]
