# Generated by Django 3.0.7 on 2025-06-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadApp', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/other_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], max_length=10)),
                ('main_image', models.ImageField(upload_to='projects/main_images/')),
                ('goal_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raised_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_images', models.ManyToManyField(blank=True, related_name='projects', to='tadApp.ProjectImage')),
            ],
        ),
    ]
