# Generated by Django 3.0.7 on 2025-06-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tadApp', '0005_project_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='other_images',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='other_images', to='tadApp.Project'),
            preserve_default=False,
        ),
    ]
