# Generated by Django 5.2.3 on 2025-06-12 13:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tadApp', '0006_auto_20250611_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default', max_length=255, null=True, verbose_name='image'),
        ),
    ]
